name: Ghost Blog CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ghostblog/ghostblog.yaml'

jobs:
  deploy-to-k8s:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Ghost YAML
        run: |
          echo "=== Applying latest YAML to Kubernetes ==="
          kubectl apply -f ghostblog/ghostblog.yaml
          
      - name: Verify Pods
        run: |
          echo "=== Waiting 10 seconds ==="
          sleep 10
          echo "=== Current Pod Status ==="
          kubectl get pods -n demo
