apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-2048
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-svc
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
